Document that _repr_*_() can return metadata
ipython/ipython pull request #11107
Opened 2018-04-30 04:07 UTC by zichongkao

This should address this open issue: https://github.com/ipython/ipython/issues/10973.

I didn't change the api docs because they already seem to have documentation for returning metadata.

2018-04-30 14:55 UTC, takluyver commented on docs/source/config/integrating.rst
> -To use this, you can define any of a number of ``_repr_*_()`` methods. Note that
This wording was actually what it was meant to say.

2018-04-30 14:55 UTC, takluyver commented on docs/source/config/integrating.rst
> +support this, ``_repr_*_()`` methods can also return a data, metadata tuple where
Let's put brackets around `(data, metadata)` for clarity.

2018-04-30 14:55 UTC, takluyver commented on docs/source/config/integrating.rst
> +metadata is a dictionary containing arbitrary key, value pairs for the frontend
I think the typical way to write this is "key-value pairs"

2018-04-30 14:55 UTC, takluyver commented on docs/source/config/integrating.rst
> +to interpret. An example use case is ``_repr_jpeg()``, which can be set to
`_repr_jpeg_()` - you missed an underscore.

2018-05-01 03:15 UTC, fperez commented
Thanks for your contribution, @zichongkao! 

@takluyver, I see the CI checks are failing, but this is a doc-only PR. Are they generically busted? Sorry that I haven't been keeping an eye on this for so long, so feel free to tell me if it's documented elsewhere or you're working on it :)

2018-05-01 03:21 UTC, fperez requested changes
Thanks for this! With a few small tweaks, should be ready for merging.

2018-05-01 06:47 UTC, takluyver commented
Hi @fperez ! I'm glad you still get time to look at the code from time to time. :-)

Some change in Jedi broke one of our tests - it's tracked as #11103, and @Carreau was investigating, but possibly someone else needs to take over on that.

2018-05-01 19:43 UTC, zichongkao commented
@fperez @takluyver Good points! Thanks for the feedback!

2018-05-01 21:55 UTC, merged

2018-05-01 21:55 UTC, fperez commented
Merged, thanks @zichongkao for your first contribution to IPython! 

Looking forward to more in the future :)