Add configurability to executing nodes.
ipython/ipython pull request #12165
Opened 2020-02-29 20:57 UTC by Carreau

A bit hacky but should help with #12151

2020-02-29 20:58 UTC, Carreau commented
cc @alexmojaki

2020-02-29 21:04 UTC, alexmojaki requested changes

2020-02-29 21:04 UTC, alexmojaki commented on IPython/core/ultratb.py
> +            style = stack_data.style_with_executing_node(style, self.color_scheme_table.active_colors.ExecutingNode)
```suggestion
            style = stack_data.style_with_executing_node(style, self.Colors.ExecutingNode)
```

2020-02-29 21:04 UTC, alexmojaki commented on IPython/core/excolors.py
> +        ExecutingNode = 'bg:#00005f'
```suggestion
        ExecutingNode = 'bg:#00005f',
```

2020-02-29 21:04 UTC, alexmojaki commented on IPython/core/excolors.py
> +        ExecutingNode = 'bg:#005f00'
```suggestion
        ExecutingNode = 'bg:#005f00',
```

Keep diffs minimal :)

2020-02-29 21:04 UTC, alexmojaki commented on IPython/core/excolors.py
> +        ExecutingNode = 'bg:#dddddd'
```suggestion
        ExecutingNode = 'bg:#dddddd',
```

2020-02-29 21:07 UTC, alexmojaki commented
Seems to me that it would be easier to first have pygments styles sorted for each option and then we could see what the executing colors look like behind syntax highlighted code.

2020-02-29 22:33 UTC, Carreau commented
> Seems to me that it would be easier to first have pygments styles sorted for each option and then we could see what the executing colors look like behind syntax highlighted code.

Yes the whole color think is a mess. I was just hoping to use this as a workaround and slowly progress toward a clean solution.

2020-07-30 21:47 UTC, Carreau commented on IPython/core/excolors.py
>          Normal = C.NoColor
```suggestion
        Normal = C.NoColor,
```

2024-09-16 09:19 UTC, closed without merging