Exceptions raised when executing notebooks via the %run magic command
ipython/ipython pull request #12301
Opened 2020-05-09 14:46 UTC by palewire

A first step toward fixing #12291. I only addressed the execution of ipynb files because I lacked the confidence to edit the complex shell operations below.

It's unclear to me if you would want the ultimately solution to be this narrowly tailored, or if you'd prefer other elements of this function to change behavior as well. If you let me know what you'd like, I can attempt to implement it.

I can verify that this modest patch did in fact work in my notebook testing.

2020-05-11 15:50 UTC, choldgraf commented
This seems good to me! Do you think we could add a test to make sure that this will properly fail when run on a notebook w/ a `%run` that doesn't work? (though I am not super familiar with ipython's testing infra...)

2020-05-11 16:00 UTC, MSeal requested changes
I think you need to change all the places with a `return` above the line you edited to instead raise the given exception (or create one). Otherwise typos or missing files will error silently and not raise as well.

2020-05-11 16:03 UTC, MSeal commented
> This seems good to me! Do you think we could add a test to make sure that this will properly fail when run on a notebook w/ a `%run` that doesn't work? (though I am not super familiar with ipython's testing infra...maybe @MSeal has a better idea than I?)

Doesn't have to be notebook specific. A test could be to call the `run` function with an execution target that will always fail and make sure it raises an exception. To be thorough, have a test for each failure path to ensure if raises an exception.

2020-05-11 17:59 UTC, palewire commented
@MSeal I've added some additional exceptions. Is that what you were after?

2020-05-11 18:17 UTC, MSeal commented
@palewire Yep. I think you missed one more: https://github.com/ipython/ipython/blob/6bde6703d7b924dfb308515e70ebd926c92fa3b2/IPython/core/magics/execution.py#L676

2020-05-11 19:49 UTC, palewire commented
Okay @MSeal, I've added that one yet too. Anything else I can do?

2020-05-11 19:56 UTC, MSeal commented
Probably to make this mergable, we need some updated or new tests in https://github.com/ipython/ipython/blob/master/IPython/core/tests/test_run.py.

Thanks for contributing and getting this fixed btw :)

2020-05-11 19:56 UTC, MSeal commented
@Carreau Can comment if there's anything else since he's the maintainer here

2020-05-12 02:33 UTC, palewire commented
I've pushed a fresh commit with some unit tests. Take a look and let me know what else I can do.

2020-05-12 15:39 UTC, choldgraf commented
Nice! It looks good to me!

2020-05-12 16:50 UTC, MSeal approved these changes
LGTM

2020-05-12 19:03 UTC, palewire commented
Thanks, guys. @Carreau, let me know if there's anything else I can do.

2020-05-31 22:57 UTC, merged

2020-05-31 22:57 UTC, Carreau commented
Thanks, looks good, sorry this ended up hidden with all the open PRs.