use pathlib in tools/gh_api.py
ipython/ipython pull request #12806
Opened 2021-02-02 20:49 UTC by PhanatosZou

This is related to #12515 
This is my first contribution here so please guide me if I'm doing anything wrong.
@Carreau, please review this PR.
Thank you.

2021-02-03 22:41 UTC, PhanatosZou commented
Kindly ask if anyone know what's wrong here? Seems like it fails the test with Python 3.8. Any advice on improvement will be appreciated. Thanks!

2021-04-03 23:39 UTC, MrMino commented
The CI failure looks unrelated. The failure is here: https://travis-ci.com/github/ipython/ipython/jobs/479778266#L773

2021-04-03 23:42 UTC, MrMino requested changes

2021-04-03 23:42 UTC, MrMino commented on tools/gh_api.py
> +    filedata = Path(filename).read_bytes()
You could improve this method further by making sure it creates `Path` only once - currently it does twice.

2024-10-27 17:45 UTC, Carreau commented
Thanks for your patience and sending this; I was not able to keep up with everything and to keep the number of PRs small I'm going to close this one; If you believe this was a mistake, feel free to comment or re-send it; 

I can't guarantee I'll get to it as I do not have the bandwidth.

2024-10-27 17:45 UTC, closed without merging