Fix for https://github.com/ipython/ipython/issues/13084
ipython/ipython pull request #13093
Opened 2021-08-15 22:30 UTC by madbird1304

Fix for [issue](https://github.com/ipython/ipython/issues/13084) caused by using shlex to quote executable path.
Sorry, [I've introduced this bug](https://github.com/ipython/ipython/pull/13052).
To fix this, let's replace shlex.quote with `subprocess.list2cmd()`. It
- uses `"` to quote path,
- performs quoting only if necessary

@MrMino , could you take a look please?
![image](https://user-images.githubusercontent.com/18216480/129494342-9d5874c4-7421-4740-8f97-2959d2972089.png)

2021-08-16 18:38 UTC, MrMino requested changes
Ugh... I didn't wanted `list2cmdline` cause it's MSC specific [but it turns out that `shlex.quote` also isn't "platform agnostic"](https://github.com/python/cpython/commit/f9a8386e44a695551a1e54e709969e90e9b96bc4). It didn't occur to me that single quotes would have different meaning to double quotes - I should've tested it on Windows.

One other argument against using `list2cmdline`: [it isn't really "public"](https://bugs.python.org/issue11827) in the same sense other methods of `subprocess` are. It's an implementation detail, not a "public API".

Furthermore, I feel like introducing MSC shell semantics on all other platforms will introduce subtle bugs and edge cases. A simple `.replace("'", "\"")` also isn't enough, since virtualenv paths can contain `"`.

At this point I'm questioning whether this should even use `shell.system`. I should probably look into creating a `argv`-style API for shell commands in magics. But let's fix this first. Any changes to that would probably need to go into 8.0, and we need to get the fix into 7.27.

I don't see any other option than using `if sys.platform=="win32": ...` here and adding quotes manually similarily to `"\"" + s + "\"".

2021-08-17 01:12 UTC, madbird1304 commented
@MrMino , you said:
> At this point I'm questioning whether this should even use shell.system.

Then let's just get rid of it?
![image](https://user-images.githubusercontent.com/18216480/129648021-82dcaa48-2c82-4919-a767-26ecc9ac0d76.png)

2021-08-17 21:27 UTC, MrMino commented
We cannot get rid of or substantially change `shell.system` until at least 8.0, and even then I'd rather not add more to an already bulky major release. The fix has to go into the next 7.x.

Coming up with something that is a valid replacement for it isn't trivial either.

Unless there's another option, I'd rather bodge it in with a `sys.platform` branch.

2021-08-18 07:54 UTC, MrMino commented on IPython/core/magics/packaging.py
> +                python = shlex.quote(python)
Branching over `" " in python` isn't necessary here.

```suggestion
        if sys.platform == "win32":
            python = "\"" + python + "\""
        else:
            python = shlex.quote(python)
```

2021-08-18 07:55 UTC, MrMino reviewed
Exactly what I had in mind :). Thanks!

If you add a whats-new entry and fix the linter errors, I'll merge.

2021-08-20 21:54 UTC, MrMino commented on IPython/core/magics/packaging.py
> +                python = shlex.quote(python)
Branching over `" " in python` isn't necessary here.

```suggestion
        if sys.platform == "win32":
            python = "\"" + python + "\""
        else:
            python = shlex.quote(python)
```

2021-08-20 21:55 UTC, MrMino commented on IPython/core/magics/packaging.py
> +                python = shlex.quote(python)
Branching over `" " in python` isn't necessary here.

```suggestion
        if sys.platform == "win32":
            python = '"' + python + '"'
        else:
            python = shlex.quote(python)
```

2021-08-20 21:58 UTC, MrMino approved these changes

2021-08-20 21:59 UTC, merged

2021-08-20 21:59 UTC, MrMino commented
Thanks @madbird1304!

2021-08-22 21:56 UTC, madbird1304 commented
Sorry for late reply. I was busy last week, so thanks for finishing that without me.