solving the type error in line 331 in ipython/core/interactiveshell.py
ipython/ipython pull request #14359
Opened 2024-03-01 22:35 UTC by DrManishSharma

List isn't subscriptable and line 331 in interactiveshell.py defines list as: 
>List[ast.NodeTransformer]
 
which causes a 

> TypeError: 'type' object is not subscriptable. 

To solve it change the line 331 to: 

> ast_transformers: List = List(

2024-03-02 12:59 UTC, krassowski requested changes
This should not be needed with correct version of `tratilets` installed. Removing generic information from the type will make errors in the codebase more likely in the future. Please see https://github.com/ipython/ipython/issues/14358#issuecomment-1974790463 for context.

2024-03-15 07:06 UTC, huangchengshun commented
![JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> _huangchengshun.comV_/~$~&/

JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
### _huangchengshun.comV****_
https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)
>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

>https://www.://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

>https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

> **huangchengshun.comV**

> JPEG_20240315_145331](https://github.com/ipython/ipython/assets/162489289/54212ef4-18b1-4272-a358-b1884e5f106d)

> huangchengshun.comV~$~&/

> JPEG_20240315_145331](https://github.com/ipython/ipytho

2024-03-19 00:09 UTC, huangchengshun commented
中国华为系统与湖南各地市/县小程序就是个盗窃贼此事我在黑客委员大会上也讨论过

2024-05-12 08:53 UTC, krassowski commented
I believe this can be closed as the issue was solved by https://github.com/ipython/ipython/pull/14353.

2024-05-12 08:53 UTC, closed without merging